package country

import (
	"fmt"
	"strings"
)

type Country struct {
	full       string
	code_two   string
	code_three string
	num        string
}

func (c *Country) Full() string {
	return c.full
}

func (c *Country) CodeTwo() string {
	return c.code_two
}

func (c *Country) CodeThree() string {
	return c.code_three
}

func (c *Country) Number() string {
	return c.num
}

func (c *Country) ExistsFull(text string) bool {
	if strings.Contains(text, strings.ToLower(c.full)) {
		return true
	} else {
		return false
	}
}

func (c *Country) ExistsTwo(text string) bool {
	if strings.Contains(text, c.code_two) {
		return true
	} else {
		return false
	}
}

func (c *Country) ExistsThree(text string) bool {
	if strings.Contains(text, c.code_three) {
		return true
	} else {
		return false
	}
}

func (c *Country) ExistsNum(text string) bool {
	if strings.Contains(text, c.num) {
		return true
	} else {
		return false
	}
}

type Options struct {
	full       bool
	two_code   bool
	three_code bool
	num        bool
}

func FindByNum(num int) *Country {
	search := fmt.Sprintf("%03d", num)
	for _, c := range countries {
		if c.ExistsNum(search) {
			return c
		}
	}
	return nil
}

func Contains(text string, options *Options) []*Country {
	text = strings.ToLower(text)
	contains := make([]*Country, 0)

	for _, c := range countries {
		if options.full && c.ExistsFull(text) || options.two_code && c.ExistsTwo(text) || options.three_code && c.ExistsThree(text) || options.num && c.ExistsNum(text) {
			contains = append(contains, c)
		}
	}

	return contains
}

var countries = [...]*Country{
	&Country{full: "Afghanistan", code_two: "AF", code_three: "AFG", num: "004"},
	&Country{full: "ALA	Aland Islands", code_two: "AX", code_three: "ALA", num: "248"},
	&Country{full: "Albania", code_two: "AL", code_three: "ALB", num: "008"},
	&Country{full: "Algeria", code_two: "DZ", code_three: "DZA", num: "012"},
	&Country{full: "American Samoa", code_two: "AS", code_three: "ASM", num: "016"},
	&Country{full: "Andorra", code_two: "AD", code_three: "AND", num: "020"},
	&Country{full: "Angola", code_two: "AO", code_three: "AGO", num: "024"},
	&Country{full: "Anguilla", code_two: "AI", code_three: "AIA", num: "660"},
	&Country{full: "Antarctica", code_two: "AQ", code_three: "ATA", num: "010"},
	&Country{full: "Antigua and Barbuda", code_two: "AG", code_three: "ATG", num: "028"},
	&Country{full: "Argentina", code_two: "AR", code_three: "ARG", num: "032"},
	&Country{full: "Armenia", code_two: "AM", code_three: "ARM", num: "051"},
	&Country{full: "Aruba", code_two: "AW", code_three: "ABW", num: "533"},
	&Country{full: "Australia", code_two: "AU", code_three: "AUS", num: "036"},
	&Country{full: "Austria", code_two: "AT", code_three: "AUT", num: "040"},
	&Country{full: "Azerbaijan", code_two: "AZ", code_three: "AZE", num: "031"},
	&Country{full: "Bahamas", code_two: "BS", code_three: "BHS", num: "044"},
	&Country{full: "Bahrain", code_two: "BH", code_three: "BHR", num: "048"},
	&Country{full: "Bangladesh", code_two: "BD", code_three: "BGD", num: "050"},
	&Country{full: "Barbados", code_two: "BB", code_three: "BRB", num: "052"},
	&Country{full: "Belarus", code_two: "BY", code_three: "BLR", num: "112"},
	&Country{full: "Belgium", code_two: "BE", code_three: "BEL", num: "056"},
	&Country{full: "Belize", code_two: "BZ", code_three: "BLZ", num: "084"},
	&Country{full: "Benin", code_two: "BJ", code_three: "BEN", num: "204"},
	&Country{full: "Bermuda", code_two: "BM", code_three: "BMU", num: "060"},
	&Country{full: "Bhutan", code_two: "BT", code_three: "BTN", num: "064"},
	&Country{full: "Bolivia", code_two: "BO", code_three: "BOL", num: "068"},
	&Country{full: "Bosnia and Herzegovina", code_two: "BA", code_three: "BIH", num: "070"},
	&Country{full: "Botswana", code_two: "BW", code_three: "BWA", num: "072"},
	&Country{full: "Bouvet Island", code_two: "BV", code_three: "BVT", num: "074"},
	&Country{full: "Brazil", code_two: "BR", code_three: "BRA", num: "076"},
	&Country{full: "British Virgin Islands", code_two: "VG", code_three: "VGB", num: "092"},
	&Country{full: "British Indian Ocean Territory", code_two: "IO", code_three: "IOT", num: "086"},
	&Country{full: "Brunei Darussalam", code_two: "BN", code_three: "BRN", num: "096"},
	&Country{full: "Bulgaria", code_two: "BG", code_three: "BGR", num: "100"},
	&Country{full: "Burkina Faso", code_two: "BF", code_three: "BFA", num: "854"},
	&Country{full: "Burundi", code_two: "BI", code_three: "BDI", num: "108"},
	&Country{full: "Cambodia", code_two: "KH", code_three: "KHM", num: "116"},
	&Country{full: "Cameroon", code_two: "CM", code_three: "CMR", num: "120"},
	&Country{full: "Canada", code_two: "CA", code_three: "CAN", num: "124"},
	&Country{full: "Cape Verde", code_two: "CV", code_three: "CPV", num: "132"},
	&Country{full: "Cayman Islands", code_two: "KY", code_three: "CYM", num: "136"},
	&Country{full: "Central African Republic", code_two: "CF", code_three: "CAF", num: "140"},
	&Country{full: "Chad", code_two: "TD", code_three: "TCD", num: "148"},
	&Country{full: "Chile", code_two: "CL", code_three: "CHL", num: "152"},
	&Country{full: "China", code_two: "CN", code_three: "CHN", num: "156"},
	&Country{full: "Hong Kong, Special Administrative Region of China", code_two: "HK", code_three: "HKG", num: "344"},
	&Country{full: "Macao, Special Administrative Region of China", code_two: "MO", code_three: "MAC", num: "446"},
	&Country{full: "Christmas Island", code_two: "CX", code_three: "CXR", num: "162"},
	&Country{full: "Cocos Islands", code_two: "CC", code_three: "CCK", num: "166"},
	&Country{full: "Colombia", code_two: "CO", code_three: "COL", num: "170"},
	&Country{full: "Comoros", code_two: "KM", code_three: "COM", num: "174"},
	&Country{full: "Congo", code_two: "CG", code_three: "COG", num: "178"},
	&Country{full: "Congo, Democratic Republic of the", code_two: "CD", code_three: "COD", num: "180"},
	&Country{full: "Cook Islands", code_two: "CK", code_three: "COK", num: "184"},
	&Country{full: "Costa Rica", code_two: "CR", code_three: "CRI", num: "188"},
	&Country{full: "Côte d'Ivoire", code_two: "CI", code_three: "CIV", num: "384"},
	&Country{full: "Croatia", code_two: "HR", code_three: "HRV", num: "191"},
	&Country{full: "Cuba", code_two: "CU", code_three: "CUB", num: "192"},
	&Country{full: "Cyprus", code_two: "CY", code_three: "CYP", num: "196"},
	&Country{full: "Czech Republic", code_two: "CZ", code_three: "CZE", num: "203"},
	&Country{full: "Denmark", code_two: "DK", code_three: "DNK", num: "208"},
	&Country{full: "Djibouti", code_two: "DJ", code_three: "DJI", num: "262"},
	&Country{full: "Dominica", code_two: "DM", code_three: "DMA", num: "212"},
	&Country{full: "Dominican Republic", code_two: "DO", code_three: "DOM", num: "214"},
	&Country{full: "Ecuador", code_two: "EC", code_three: "ECU", num: "218"},
	&Country{full: "Egypt", code_two: "EG", code_three: "EGY", num: "818"},
	&Country{full: "El Salvador", code_two: "SV", code_three: "SLV", num: "222"},
	&Country{full: "Equatorial Guinea", code_two: "GQ", code_three: "GNQ", num: "226"},
	&Country{full: "Eritrea", code_two: "ER", code_three: "ERI", num: "232"},
	&Country{full: "Estonia", code_two: "EE", code_three: "EST", num: "233"},
	&Country{full: "Ethiopia", code_two: "ET", code_three: "ETH", num: "231"},
	&Country{full: "Falkland Islands", code_two: "FK", code_three: "FLK", num: "238"},
	&Country{full: "Faroe Islands", code_two: "FO", code_three: "FRO", num: "234"},
	&Country{full: "Fiji", code_two: "FJ", code_three: "FJI", num: "242"},
	&Country{full: "Finland", code_two: "FI", code_three: "FIN", num: "246"},
	&Country{full: "France", code_two: "FR", code_three: "FRA", num: "250"},
	&Country{full: "French Guiana", code_two: "GF", code_three: "GUF", num: "254"},
	&Country{full: "French Polynesia", code_two: "PF", code_three: "PYF", num: "258"},
	&Country{full: "French Southern Territories", code_two: "TF", code_three: "ATF", num: "260"},
	&Country{full: "Gabon", code_two: "GA", code_three: "GAB", num: "266"},
	&Country{full: "Gambia", code_two: "GM", code_three: "GMB", num: "270"},
	&Country{full: "Georgia", code_two: "GE", code_three: "GEO", num: "268"},
	&Country{full: "Germany", code_two: "DE", code_three: "DEU", num: "276"},
	&Country{full: "Ghana", code_two: "GH", code_three: "GHA", num: "288"},
	&Country{full: "Gibraltar", code_two: "GI", code_three: "GIB", num: "292"},
	&Country{full: "Greece", code_two: "GR", code_three: "GRC", num: "300"},
	&Country{full: "Greenland", code_two: "GL", code_three: "GRL", num: "304"},
	&Country{full: "Grenada", code_two: "GD", code_three: "GRD", num: "308"},
	&Country{full: "Guadeloupe", code_two: "GP", code_three: "GLP", num: "312"},
	&Country{full: "Guam", code_two: "GU", code_three: "GUM", num: "316"},
	&Country{full: "Guatemala", code_two: "GT", code_three: "GTM", num: "320"},
	&Country{full: "Guernsey", code_two: "GG", code_three: "GGY", num: "831"},
	&Country{full: "Guinea", code_two: "GN", code_three: "GIN", num: "324"},
	&Country{full: "Guinea-Bissau", code_two: "GW", code_three: "GNB", num: "624"},
	&Country{full: "Guyana", code_two: "GY", code_three: "GUY", num: "328"},
	&Country{full: "Haiti", code_two: "HT", code_three: "HTI", num: "332"},
	&Country{full: "Heard Island and Mcdonald Islands", code_two: "HM", code_three: "HMD", num: "334"},
	&Country{full: "Holy See", code_two: "VA", code_three: "VAT", num: "336"},
	&Country{full: "Honduras", code_two: "HN", code_three: "HND", num: "340"},
	&Country{full: "Hungary", code_two: "HU", code_three: "HUN", num: "348"},
	&Country{full: "Iceland", code_two: "IS", code_three: "ISL", num: "352"},
	&Country{full: "India", code_two: "IN", code_three: "IND", num: "356"},
	&Country{full: "Indonesia", code_two: "ID", code_three: "IDN", num: "360"},
	&Country{full: "Iran, Islamic Republic of", code_two: "IR", code_three: "IRN", num: "364"},
	&Country{full: "Iraq", code_two: "IQ", code_three: "IRQ", num: "368"},
	&Country{full: "Ireland", code_two: "IE", code_three: "IRL", num: "372"},
	&Country{full: "Isle of Man", code_two: "IM", code_three: "IMN", num: "833"},
	&Country{full: "Israel", code_two: "IL", code_three: "ISR", num: "376"},
	&Country{full: "Italy", code_two: "IT", code_three: "ITA", num: "380"},
	&Country{full: "Jamaica", code_two: "JM", code_three: "JAM", num: "388"},
	&Country{full: "Japan", code_two: "JP", code_three: "JPN", num: "392"},
	&Country{full: "Jersey", code_two: "JE", code_three: "JEY", num: "832"},
	&Country{full: "Jordan", code_two: "JO", code_three: "JOR", num: "400"},
	&Country{full: "Kazakhstan", code_two: "KZ", code_three: "KAZ", num: "398"},
	&Country{full: "Kenya", code_two: "KE", code_three: "KEN", num: "404"},
	&Country{full: "Kiribati", code_two: "KI", code_three: "KIR", num: "296"},
	&Country{full: "Korea, Democratic People's Republic of", code_two: "KP", code_three: "PRK", num: "408"},
	&Country{full: "Korea, Republic of", code_two: "KR", code_three: "KOR", num: "410"},
	&Country{full: "Kuwait", code_two: "KW", code_three: "KWT", num: "414"},
	&Country{full: "Kyrgyzstan", code_two: "KG", code_three: "KGZ", num: "417"},
	&Country{full: "Lao PDR", code_two: "LA", code_three: "LAO", num: "418"},
	&Country{full: "Latvia", code_two: "LV", code_three: "LVA", num: "428"},
	&Country{full: "Lebanon", code_two: "LB", code_three: "LBN", num: "422"},
	&Country{full: "Lesotho", code_two: "LS", code_three: "LSO", num: "426"},
	&Country{full: "Liberia", code_two: "LR", code_three: "LBR", num: "430"},
	&Country{full: "Libya", code_two: "LY", code_three: "LBY", num: "434"},
	&Country{full: "Liechtenstein", code_two: "LI", code_three: "LIE", num: "438"},
	&Country{full: "Lithuania", code_two: "LT", code_three: "LTU", num: "440"},
	&Country{full: "Luxembourg", code_two: "LU", code_three: "LUX", num: "442"},
	&Country{full: "Macedonia", code_two: "MK", code_three: "MKD", num: "807"},
	&Country{full: "Madagascar", code_two: "MG", code_three: "MDG", num: "450"},
	&Country{full: "Malawi", code_two: "MW", code_three: "MWI", num: "454"},
	&Country{full: "Malaysia", code_two: "MY", code_three: "MYS", num: "458"},
	&Country{full: "Maldives", code_two: "MV", code_three: "MDV", num: "462"},
	&Country{full: "Mali", code_two: "ML", code_three: "MLI", num: "466"},
	&Country{full: "Malta", code_two: "MT", code_three: "MLT", num: "470"},
	&Country{full: "Marshall Islands", code_two: "MH", code_three: "MHL", num: "584"},
	&Country{full: "Martinique", code_two: "MQ", code_three: "MTQ", num: "474"},
	&Country{full: "Mauritania", code_two: "MR", code_three: "MRT", num: "478"},
	&Country{full: "Mauritius", code_two: "MU", code_three: "MUS", num: "480"},
	&Country{full: "Mayotte", code_two: "YT", code_three: "MYT", num: "175"},
	&Country{full: "Mexico", code_two: "MX", code_three: "MEX", num: "484"},
	&Country{full: "Micronesia", code_two: "FM", code_three: "FSM", num: "583"},
	&Country{full: "Moldova", code_two: "MD", code_three: "MDA", num: "498"},
	&Country{full: "Monaco", code_two: "MC", code_three: "MCO", num: "492"},
	&Country{full: "Mongolia", code_two: "MN", code_three: "MNG", num: "496"},
	&Country{full: "Montenegro", code_two: "ME", code_three: "MNE", num: "499"},
	&Country{full: "Montserrat", code_two: "MS", code_three: "MSR", num: "500"},
	&Country{full: "Morocco", code_two: "MA", code_three: "MAR", num: "504"},
	&Country{full: "Mozambique", code_two: "MZ", code_three: "MOZ", num: "508"},
	&Country{full: "Myanmar", code_two: "MM", code_three: "MMR", num: "104"},
	&Country{full: "Namibia", code_two: "NA", code_three: "NAM", num: "516"},
	&Country{full: "Nauru", code_two: "NR", code_three: "NRU", num: "520"},
	&Country{full: "Nepal", code_two: "NP", code_three: "NPL", num: "524"},
	&Country{full: "Netherlands", code_two: "NL", code_three: "NLD", num: "528"},
	&Country{full: "Netherlands Antilles", code_two: "AN", code_three: "ANT", num: "530"},
	&Country{full: "New Caledonia", code_two: "NC", code_three: "NCL", num: "540"},
	&Country{full: "New Zealand", code_two: "NZ", code_three: "NZL", num: "554"},
	&Country{full: "Nicaragua", code_two: "NI", code_three: "NIC", num: "558"},
	&Country{full: "Niger", code_two: "NE", code_three: "NER", num: "562"},
	&Country{full: "Nigeria", code_two: "NG", code_three: "NGA", num: "566"},
	&Country{full: "Niue", code_two: "NU", code_three: "NIU", num: "570"},
	&Country{full: "Norfolk Island", code_two: "NF", code_three: "NFK", num: "574"},
	&Country{full: "Northern Mariana Islands", code_two: "MP", code_three: "MNP", num: "580"},
	&Country{full: "Norway", code_two: "NO", code_three: "NOR", num: "578"},
	&Country{full: "Oman", code_two: "OM", code_three: "OMN", num: "512"},
	&Country{full: "Pakistan", code_two: "PK", code_three: "PAK", num: "586"},
	&Country{full: "Palau", code_two: "PW", code_three: "PLW", num: "585"},
	&Country{full: "Palestine", code_two: "PS", code_three: "PSE", num: "275"},
	&Country{full: "Panama", code_two: "PA", code_three: "PAN", num: "591"},
	&Country{full: "Papua New Guinea", code_two: "PG", code_three: "PNG", num: "598"},
	&Country{full: "Paraguay", code_two: "PY", code_three: "PRY", num: "600"},
	&Country{full: "Peru", code_two: "PE", code_three: "PER", num: "604"},
	&Country{full: "Philippines", code_two: "PH", code_three: "PHL", num: "608"},
	&Country{full: "Pitcairn", code_two: "PN", code_three: "PCN", num: "612"},
	&Country{full: "Poland", code_two: "PL", code_three: "POL", num: "616"},
	&Country{full: "Portugal", code_two: "PT", code_three: "PRT", num: "620"},
	&Country{full: "Puerto Rico", code_two: "PR", code_three: "PRI", num: "630"},
	&Country{full: "Qatar", code_two: "QA", code_three: "QAT", num: "634"},
	&Country{full: "Réunion", code_two: "RE", code_three: "REU", num: "638"},
	&Country{full: "Romania", code_two: "RO", code_three: "ROU", num: "642"},
	&Country{full: "Russian Federation", code_two: "RU", code_three: "RUS", num: "643"},
	&Country{full: "Rwanda", code_two: "RW", code_three: "RWA", num: "646"},
	&Country{full: "Saint-Barthélemy", code_two: "BL", code_three: "BLM", num: "652"},
	&Country{full: "Saint Helena", code_two: "SH", code_three: "SHN", num: "654"},
	&Country{full: "Saint Kitts and Nevis", code_two: "KN", code_three: "KNA", num: "659"},
	&Country{full: "Saint Lucia", code_two: "LC", code_three: "LCA", num: "662"},
	&Country{full: "Saint-Martin", code_two: "MF", code_three: "MAF", num: "663"},
	&Country{full: "Saint Pierre and Miquelon", code_two: "PM", code_three: "SPM", num: "666"},
	&Country{full: "Saint Vincent and Grenadines", code_two: "VC", code_three: "VCT", num: "670"},
	&Country{full: "Samoa", code_two: "WS", code_three: "WSM", num: "882"},
	&Country{full: "San Marino", code_two: "SM", code_three: "SMR", num: "674"},
	&Country{full: "Sao Tome and Principe", code_two: "ST", code_three: "STP", num: "678"},
	&Country{full: "Saudi Arabia", code_two: "SA", code_three: "SAU", num: "682"},
	&Country{full: "Senegal", code_two: "SN", code_three: "SEN", num: "686"},
	&Country{full: "Serbia", code_two: "RS", code_three: "SRB", num: "688"},
	&Country{full: "Seychelles", code_two: "SC", code_three: "SYC", num: "690"},
	&Country{full: "Sierra Leone", code_two: "SL", code_three: "SLE", num: "694"},
	&Country{full: "Singapore", code_two: "SG", code_three: "SGP", num: "702"},
	&Country{full: "Slovakia", code_two: "SK", code_three: "SVK", num: "703"},
	&Country{full: "Slovenia", code_two: "SI", code_three: "SVN", num: "705"},
	&Country{full: "Solomon Islands", code_two: "SB", code_three: "SLB", num: "090"},
	&Country{full: "Somalia", code_two: "SO", code_three: "SOM", num: "706"},
	&Country{full: "South Africa", code_two: "ZA", code_three: "ZAF", num: "710"},
	&Country{full: "South Georgia and the South Sandwich Islands", code_two: "GS", code_three: "SGS", num: "239"},
	&Country{full: "South Sudan", code_two: "SS", code_three: "SSD", num: "728"},
	&Country{full: "Spain", code_two: "ES", code_three: "ESP", num: "724"},
	&Country{full: "Sri Lanka", code_two: "LK", code_three: "LKA", num: "144"},
	&Country{full: "Sudan", code_two: "SD", code_three: "SDN", num: "736"},
	&Country{full: "Suriname", code_two: "SR", code_three: "SUR", num: "740"},
	&Country{full: "Svalbard and Jan Mayen Islands", code_two: "SJ", code_three: "SJM", num: "744"},
	&Country{full: "Swaziland", code_two: "SZ", code_three: "SWZ", num: "748"},
	&Country{full: "Sweden", code_two: "SE", code_three: "SWE", num: "752"},
	&Country{full: "Switzerland", code_two: "CH", code_three: "CHE", num: "756"},
	&Country{full: "Syrian Arab Republic (Syria)", code_two: "SY", code_three: "SYR", num: "760"},
	&Country{full: "Taiwan, Republic of China", code_two: "TW", code_three: "TWN", num: "158"},
	&Country{full: "Tajikistan", code_two: "TJ", code_three: "TJK", num: "762"},
	&Country{full: "Tanzania *, United Republic of", code_two: "TZ", code_three: "TZA", num: "834"},
	&Country{full: "Thailand", code_two: "TH", code_three: "THA", num: "764"},
	&Country{full: "Timor-Leste", code_two: "TL", code_three: "TLS", num: "626"},
	&Country{full: "Togo", code_two: "TG", code_three: "TGO", num: "768"},
	&Country{full: "Tokelau", code_two: "TK", code_three: "TKL", num: "772"},
	&Country{full: "Tonga", code_two: "TO", code_three: "TON", num: "776"},
	&Country{full: "Trinidad and Tobago", code_two: "TT", code_three: "TTO", num: "780"},
	&Country{full: "Tunisia", code_two: "TN", code_three: "TUN", num: "788"},
	&Country{full: "Turkey", code_two: "TR", code_three: "TUR", num: "792"},
	&Country{full: "Turkmenistan", code_two: "TM", code_three: "TKM", num: "795"},
	&Country{full: "Turks and Caicos Islands", code_two: "TC", code_three: "TCA", num: "796"},
	&Country{full: "Tuvalu", code_two: "TV", code_three: "TUV", num: "798"},
	&Country{full: "Uganda", code_two: "UG", code_three: "UGA", num: "800"},
	&Country{full: "Ukraine", code_two: "UA", code_three: "UKR", num: "804"},
	&Country{full: "United Arab Emirates", code_two: "AE", code_three: "ARE", num: "784"},
	&Country{full: "United Kingdom", code_two: "GB", code_three: "GBR", num: "826"},
	&Country{full: "United States of America", code_two: "US", code_three: "USA", num: "840"},
	&Country{full: "United States Minor Outlying Islands", code_two: "UM", code_three: "UMI", num: "581"},
	&Country{full: "Uruguay", code_two: "UY", code_three: "URY", num: "858"},
	&Country{full: "Uzbekistan", code_two: "UZ", code_three: "UZB", num: "860"},
	&Country{full: "Vanuatu", code_two: "VU", code_three: "VUT", num: "548"},
	&Country{full: "Venezuela", code_two: "VE", code_three: "VEN", num: "862"},
	&Country{full: "Viet Nam", code_two: "VN", code_three: "VNM", num: "704"},
	&Country{full: "Virgin Islands, US", code_two: "VI", code_three: "VIR", num: "850"},
	&Country{full: "Wallis and Futuna Islands", code_two: "WF", code_three: "WLF", num: "876"},
	&Country{full: "Western Sahara", code_two: "EH", code_three: "ESH", num: "732"},
	&Country{full: "Yemen", code_two: "YE", code_three: "YEM", num: "887"},
	&Country{full: "Zambia", code_two: "ZM", code_three: "ZMB", num: "894"},
	&Country{full: "Zimbabwe", code_two: "ZW", code_three: "ZWE", num: "716"},
}

var countries_full = [...]string{
	"China",
	"India",
	"United States",
	"Indonesia",
	"Brazil",
	"Pakistan",
	"Nigeria",
	"Bangladesh",
	"Russia",
	"Japan",
	"Mexico",
	"Philippines",
	"Ethiopia",
	"Vietnam",
	"Egypt",
	"Congo",
	"Germany",
	"Iran",
	"Turkey",
	"Thailand",
	"France",
	"United Kingdom",
	"Italy",
	"South Africa",
	"Tanzania",
	"Myanmar",
	"South Korea",
	"Colombia",
	"Kenya",
	"Spain",
	"Argentina",
	"Ukraine",
	"Sudan",
	"Algeria",
	"Poland",
	"Uganda",
	"Iraq",
	"Canada",
	"Morocco",
	"Saudi Arabia",
	"Uzbekistan",
	"Malaysia",
	"Peru",
	"Venezuela",
	"Nepal",
	"Ghana",
	"Afghanistan",
	"Yemen",
	"Mozambique",
	"Angola",
	"Australia",
	"North Korea",
	"Taiwan",
	"Cameroon",
	"Ivory Coast",
	"Madagascar",
	"Sri Lanka",
	"Niger",
	"Romania",
	"Burkina Faso",
	"Syria",
	"Mali",
	"Chile",
	"Kazakhstan",
	"Netherlands",
	"Malawi",
	"Ecuador",
	"Guatemala",
	"Zambia",
	"Cambodia",
	"Senegal",
	"Chad",
	"Zimbabwe",
	"Guinea",
	"South Sudan",
	"Rwanda",
	"Belgium",
	"Tunisia",
	"Cuba",
	"Somalia",
	"Haiti",
	"Bolivia",
	"Greece",
	"Benin",
	"Czech Republic",
	"Portugal",
	"Burundi",
	"Dominican Republic",
	"Sweden",
	"Jordan",
	"United Arab Emirates",
	"Hungary",
	"Azerbaijan",
	"Belarus",
	"Austria",
	"Honduras",
	"Israel",
	"Tajikistan",
	"Switzerland",
	"Papua New Guinea",
	"Hong Kong",
	"Bulgaria",
	"Togo",
	"Serbia",
	"Sierra Leone",
	"Paraguay",
	"El Salvador",
	"Laos",
	"Libya",
	"Nicaragua",
	"Kyrgyzstan",
	"Lebanon",
	"Denmark",
	"Singapore",
	"Finland",
	"Slovakia",
	"Eritrea",
	"Norway",
	"Central African Republic",
	"Costa Rica",
	"Palestine",
	"Ireland",
	"New Zealand",
	"Turkmenistan",
	"Republic of the Congo",
	"Oman",
	"Croatia",
	"Kuwait",
	"Liberia",
	"Panama",
	"Georgia",
	"Mauritania",
	"Moldova",
	"Bosnia and Herzegovina",
	"Uruguay",
	"Puerto Rico",
	"Mongolia",
	"Armenia",
	"Albania",
	"Lithuania",
	"Jamaica",
	"Qatar",
	"Namibia",
	"Botswana",
	"Macedonia",
	"Slovenia",
	"Latvia",
	"Lesotho",
	"The Gambia",
	"Kosovo",
	"Gabon",
	"Guinea-Bissau",
	"Bahrain",
	"Trinidad and Tobago",
	"Estonia",
	"Mauritius",
	"Equatorial Guinea",
	"East Timor",
	"Swaziland",
	"Djibouti",
	"Fiji",
	"Cyprus",
	"Comoros",
	"Bhutan",
	"Guyana",
	"Macau",
	"Solomon Islands",
	"Montenegro",
	"Western Sahara",
	"Luxembourg",
	"Suriname",
	"Cape Verde",
	"Transnistria",
	"Malta",
	"Brunei",
	"Belize",
	"Bahamas",
	"Maldives",
	"Iceland",
	"Northern Cyprus",
	"Barbados",
	"Vanuatu",
	"French Polynesia",
	"New Caledonia",
	"Abkhazia",
	"Samoa",
	"São Tomé and Príncipe",
	"Saint Lucia",
	"Guam",
	"Curaçao",
	"Nagorno-Karabakh Republic",
	"Kiribati",
	"Aruba",
	"Saint Vincent and the Grenadines",
	"United States Virgin Islands",
	"Grenada",
	"Tonga",
	"Federated States of Micronesia",
	"Jersey",
	"Seychelles",
	"Antigua and Barbuda",
	"Isle of Man",
	"Andorra",
	"Dominica",
	"Guernsey",
	"Bermuda",
	"Cayman Islands",
	"American Samoa",
	"Northern Mariana Islands",
	"Greenland",
	"Marshall Islands",
	"South Ossetia",
	"Faroe Islands",
	"Saint Kitts and Nevis",
	"Saint Maarten",
	"Monaco",
	"Liechtenstein",
	"Flag of Saint-Martin",
	"Gibraltar",
	"San Marino",
	"Turks and Caicos Islands",
	"British Virgin Islands",
	"Bonaire",
	"Cook Islands",
	"Palau",
	"Anguilla",
	"Wallis and Futuna",
	"Tuvalu",
	"Nauru",
	"Saint Barthélemy",
	"Saint Pierre and Miquelon",
	"Montserrat",
	"Saint Helena",
	"Saint Eustatius",
	"Falkland Islands",
	"Norfolk Island",
	"Christmas Island",
	"Saba",
	"Niue",
	"Tokelau",
	"Vatican City",
	"Cocos",
	"Pitcairn Islands",
}
